### ISSUE TITLE
报错list index out of range

### ISSUE THREAD

**Issue by BensonLaffey** [IshtarTang/lofterSpider#11]
运行l4和l8均出现IndexError:list index out of range
<img width="662" alt="屏幕截图 2024-05-17 104904" src="https://github.com/IshtarTang/lofterSpider/assets/42732878/dc560555-ae0d-400e-9470-2541288b9b04">
<img width="811" alt="屏幕截图 2024-05-17 104932 - 副本" src="https://github.com/IshtarTang/lofterSpider/assets/42732878/04c42c80-24f7-435e-adbf-33e06404b876">
<img width="496" alt="屏幕截图 2024-05-17 105154" src="https://github.com/IshtarTang/lofterSpider/assets/42732878/eea8b38d-83de-48cc-bdfc-e886e2282d97">

**Comment by zhaohuijun110** [comment]
请问是如何解决的？我也遇到了这个问题

**Comment by zhaohuijun110** [comment]
请问是如何解决的？我也遇到了这个问题
