### ISSUE TITLE
也许能通过下载具体年月下的作品来迂回的解决tag模式1200限制的问题？

### ISSUE THREAD

**Issue by Cynthia0329** [IshtarTang/lofterSpider#12]
我看了下，目前tag模式是用的网页端的接口
```
https://www.lofter.com/tag/xxx/new
```

有最大数量（1200）的限制？

但移动端现在有个新接口，感觉可以通过自己手动筛选年月来迂回的解决这个问题？
理想状态是也可以通过年月遍历这个接口获取全部
（不过也不知道这个是否会有限制）
```
https://api.lofter.com/newapi/tagPosts.json
```

![image](https://github.com/IshtarTang/lofterSpider/assets/30437028/373587ad-9d97-4205-8bd7-ef43ac6fa0c7)

对应app端下面这个功能，能获取 tag-具体年月下-按热度排序的作品
![171845a4dc44c6b4ac39d45293d0630](https://github.com/IshtarTang/lofterSpider/assets/30437028/ca93aa3d-2e53-4f18-8c27-fd6a8bc45f0d)

抓了下包，对Python不是非常很了解，只能拜托大大研究下这个是否可行了TUT
不知道能不能爬取app上的接口数据

**Comment by IshtarTang** [comment]
谢谢你帮忙调试，爬app是可行的，但是因为现在用的是Pc端的接口，弄移动端的话从爬取到解析保存基本上是要全部重写，短时间内不会考虑更新爬app，抱歉了
