### ISSUE TITLE
保存自己的推荐应该使用什么链接地址呢？

### ISSUE THREAD

**Issue by slrying** [IshtarTang/lofterSpider#13]
您好，用like2保存喜欢一直很顺利，但是保存自己的推荐不知道该使用什么地址，试了几个一直显示“链接与模式不匹配”
抱歉打扰，非常感谢

**Comment by IshtarTang** [comment]
不是匹配问题，是某次网站更新添了验证，我代码没更新所以报这个错。现在修好了，还是用个人主页的链接就行
