### ISSUE TITLE
l9 blogId的获取失败（好像登陆失败）

### ISSUE THREAD

**Issue by KKH0013** [IshtarTang/lofterSpider#16]
![code](https://github.com/user-attachments/assets/5e4fc546-33a5-4acb-9476-ecc3a8c98860)
![web](https://github.com/user-attachments/assets/231e538d-9af5-4ead-9aea-b2454b414f30)

**Comment by KKH0013** [comment]
解决了

**Comment by zhaohuijun110** [comment]
请问是如何解决的？我也遇到了这个问题

**Comment by KKH0013** [comment]
> 请问如何解决？我也遇到了这个问题

我是login_info里的授权码没填完整

**Comment by zhaohuijun110** [comment]
请问现在代码，你还能运行成功吗？因为我尝试了几次授权码，都报错误list index out of range
