### ISSUE TITLE
QQ登录 已验证 可运行

### ISSUE THREAD

**Issue by Aha-Eureka** [IshtarTang/lofterSpider#17]
谢谢大大的代码！

如标题，于2024年7月13日运行 `l13` 用QQ登录，成功运行

电脑: Apple M1 Pro

mode: like2

<img width="1093" alt="Screenshot 2024-07-13 at 9 20 02 PM" src="https://github.com/user-attachments/assets/251dd63f-ed63-4ba1-8bf6-43078eec17ba">

- 因为是用QQ登录，所以无需在`l13`里面修改 `phone_number` 也无需填写 `password` (如下图所示)
<img width="873" alt="Screenshot 2024-07-13 at 9 27 44 PM" src="https://github.com/user-attachments/assets/2371bc89-8a1b-483b-8397-4d189d6a3adf">

**Comment by IshtarTang** [comment]
感谢反馈！
