### ISSUE TITLE
图片下载顺序错误

### ISSUE THREAD

**Issue by newusername2022** [IshtarTang/lofterSpider#3]
你好，谢谢写了这个！
我发现在下载作者博客图片以后图片的顺序不是原博客作者贴的顺序，请问有办法解决嘛？
下载的是 https://manon09.lofter.com/ 里的所有图片，用了`l4_author_img.py`。

**Comment by IshtarTang** [comment]
抱歉这么久才处理，刚更新成按原博客顺序的了

**Comment by newusername2022** [comment]
好的，非常感谢！！冒昧问下有计划继续那个合并作者所有的博客（包括图片和无标题的文字）嘛？

**Comment by IshtarTang** [comment]
有，但最近在准备考试，如果考过了能立马开始写，大概六月初，没考过的话可能还得再拖一下

**Comment by newusername2022** [comment]
好的，如果有需要帮忙的地方尽请开口～虽然我也只是三脚猫的水平
