### ISSUE TITLE
lxml.etree.SerialisationError: IO_ENCODER

### ISSUE THREAD

**Issue by newusername2022** [IshtarTang/lofterSpider#4]
我在用通用模板的时候碰到了这个`lxml.etree.SerialisationError: IO_ENCODER`，
搜了一下，在`parse_template.py`的第35行的`etree.tostring(temp)`里面加了一个`encoding='utf-8'`解决了问题：

```python3
open("test.html", "w", encoding="utf-8").write(etree.tostring(parse,encoding='utf-8').decode("utf-8"))
```

因为太短了就不提merge了

**Comment by IshtarTang** [comment]
已修改
