### ISSUE TITLE
是否考虑添加收录图片+文字并且根据文章分类到文件夹？

### ISSUE THREAD

**Issue by acyanbird** [IshtarTang/lofterSpider#6]
您好，可能说的不太清楚，但是有些文章是包含图片和文字的，是否能够将收录模式更改成一篇文章是一个文件夹，里面包括图片和txt呢？我们正在进行资源站建设所以量比较大……就用了您的爬虫啦，非常感谢。有些太太授权之后也无法提供所有的原文了，所以图片和 txt 分开收录，到时候拼在一起也挺麻烦的。不知道您是否有时间进行更新？

https://msy60048.lofter.com/view
目前遇到困难的是收录这位太太的文章，您可以看一下。

顺便，好兆头我也磕一口！

**Comment by IshtarTang** [comment]
我没太明白，你运行的是哪个程序？是想收录图片博客下的配文还是文字博客里的插图？

**Comment by acyanbird** [comment]
https://msy60048.lofter.com/
我想爬这位太太的主页，希望得到的结果是每一篇是一个文件夹，里面包含图片和文字。这个请求有点冒昧，但请问您有意做这个功能吗？
非常感谢w

**Comment by IshtarTang** [comment]
我不知道你有没有运行过项目里的 l4 和 l9，如果你只是要把结果文件里的图片/文字各自放到文件夹里，那不麻烦我很快能给你弄出来。但是如果你需要的内容包括图片下的配文，那就就得把l4和l9整合在一起并且调整很多细节，要做的话需要些时间，之前有考虑过做合并，但是目前的功能对我来说够用，所以暂时不打算做。

**Comment by acyanbird** [comment]
啊这样，我们确实需要图片下的配文，那就不打扰啦。其他的功能也给我们很大的帮助，非常感谢您！请问您的代码基于什么许可证发布呢？我们可能会基于您的代码做一些调整开发这个功能。

**Comment by IshtarTang** [comment]
是这样，我知道协议都是允许商用的，而这个程序我不允许它被用来盈利，所以没法让它直接按某个协议发布。我不介意基于我的代码写功能，我也想过要是有人改代码得遵守哪些条例，但我也不知道自己写条例放那有没有效，就 一直搁置着了
