### ISSUE TITLE
l4.py下载lofter博主所有图片，下载完删除所有归档信息，如果lofter博主有更新，得重新“全部”下载了？

### ISSUE THREAD

**Issue by jiqing112** [IshtarTang/lofterSpider#7]
l4.py下载lofter博主所有图片，下载完删除所有归档信息，如果lofter博主有更新，得重新“全部”下载了？

我看程序可以单独设置时间段，可以保存当前是时间点吗，以后有博主有更新，从上次时间点下载。

**Comment by IshtarTang** [comment]
归档信息是用来进度的，没进度就新建一个，删掉自然就从头开始下载了。
不能保存当前时间点，但是你可以手动把时间记下来，下次把start_time设成上次记的时间就行，反正我一直是这么干的
